// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteQueue(arg1, arg2, arg3) {
  return window['go']['queue']['QueueService']['DeleteQueue'](arg1, arg2, arg3);
}

export function GetQueues(arg1) {
  return window['go']['queue']['QueueService']['GetQueues'](arg1);
}

export function PauseQueue(arg1, arg2) {
  return window['go']['queue']['QueueService']['PauseQueue'](arg1, arg2);
}

export function UnpauseQueue(arg1, arg2) {
  return window['go']['queue']['QueueService']['UnpauseQueue'](arg1, arg2);
}
