// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {queue} from '../models';

export function DeleteQueue(arg1:number,arg2:string,arg3:boolean):Promise<void>;

export function GetQueues(arg1:number):Promise<queue.QueuesData>;

export function PauseQueue(arg1:number,arg2:string):Promise<void>;

export function UnpauseQueue(arg1:number,arg2:string):Promise<void>;
