// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveAllPendingTasks(arg1, arg2) {
  return window['go']['queue']['QueueService']['ArchiveAllPendingTasks'](arg1, arg2);
}

export function ArchiveAllRetryTasks(arg1, arg2) {
  return window['go']['queue']['QueueService']['ArchiveAllRetryTasks'](arg1, arg2);
}

export function ArchiveAllScheduledTasks(arg1, arg2) {
  return window['go']['queue']['QueueService']['ArchiveAllScheduledTasks'](arg1, arg2);
}

export function ArchiveTask(arg1, arg2, arg3) {
  return window['go']['queue']['QueueService']['ArchiveTask'](arg1, arg2, arg3);
}

export function CancelActiveTask(arg1, arg2) {
  return window['go']['queue']['QueueService']['CancelActiveTask'](arg1, arg2);
}

export function DeleteAllArchivedTasks(arg1, arg2) {
  return window['go']['queue']['QueueService']['DeleteAllArchivedTasks'](arg1, arg2);
}

export function DeleteAllCompletedTasks(arg1, arg2) {
  return window['go']['queue']['QueueService']['DeleteAllCompletedTasks'](arg1, arg2);
}

export function DeleteAllPendingTasks(arg1, arg2) {
  return window['go']['queue']['QueueService']['DeleteAllPendingTasks'](arg1, arg2);
}

export function DeleteAllRetryTasks(arg1, arg2) {
  return window['go']['queue']['QueueService']['DeleteAllRetryTasks'](arg1, arg2);
}

export function DeleteAllScheduledTasks(arg1, arg2) {
  return window['go']['queue']['QueueService']['DeleteAllScheduledTasks'](arg1, arg2);
}

export function DeleteQueue(arg1, arg2, arg3) {
  return window['go']['queue']['QueueService']['DeleteQueue'](arg1, arg2, arg3);
}

export function DeleteTask(arg1, arg2, arg3) {
  return window['go']['queue']['QueueService']['DeleteTask'](arg1, arg2, arg3);
}

export function GetQueueDetail(arg1, arg2) {
  return window['go']['queue']['QueueService']['GetQueueDetail'](arg1, arg2);
}

export function GetQueues(arg1) {
  return window['go']['queue']['QueueService']['GetQueues'](arg1);
}

export function ListActiveTasks(arg1, arg2, arg3, arg4) {
  return window['go']['queue']['QueueService']['ListActiveTasks'](arg1, arg2, arg3, arg4);
}

export function ListArchivedTasks(arg1, arg2, arg3, arg4) {
  return window['go']['queue']['QueueService']['ListArchivedTasks'](arg1, arg2, arg3, arg4);
}

export function ListCompletedTasks(arg1, arg2, arg3, arg4) {
  return window['go']['queue']['QueueService']['ListCompletedTasks'](arg1, arg2, arg3, arg4);
}

export function ListPendingTasks(arg1, arg2, arg3, arg4) {
  return window['go']['queue']['QueueService']['ListPendingTasks'](arg1, arg2, arg3, arg4);
}

export function ListRetryTasks(arg1, arg2, arg3, arg4) {
  return window['go']['queue']['QueueService']['ListRetryTasks'](arg1, arg2, arg3, arg4);
}

export function ListScheduledTasks(arg1, arg2, arg3, arg4) {
  return window['go']['queue']['QueueService']['ListScheduledTasks'](arg1, arg2, arg3, arg4);
}

export function PauseQueue(arg1, arg2) {
  return window['go']['queue']['QueueService']['PauseQueue'](arg1, arg2);
}

export function RunAllArchivedTasks(arg1, arg2) {
  return window['go']['queue']['QueueService']['RunAllArchivedTasks'](arg1, arg2);
}

export function RunAllRetryTasks(arg1, arg2) {
  return window['go']['queue']['QueueService']['RunAllRetryTasks'](arg1, arg2);
}

export function RunAllScheduledTasks(arg1, arg2) {
  return window['go']['queue']['QueueService']['RunAllScheduledTasks'](arg1, arg2);
}

export function RunTask(arg1, arg2, arg3) {
  return window['go']['queue']['QueueService']['RunTask'](arg1, arg2, arg3);
}

export function UnpauseQueue(arg1, arg2) {
  return window['go']['queue']['QueueService']['UnpauseQueue'](arg1, arg2);
}
