// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {queue} from '../models';

export function ArchiveAllPendingTasks(arg1:number,arg2:string):Promise<queue.BulkActionResult>;

export function ArchiveAllRetryTasks(arg1:number,arg2:string):Promise<queue.BulkActionResult>;

export function ArchiveAllScheduledTasks(arg1:number,arg2:string):Promise<queue.BulkActionResult>;

export function ArchiveTask(arg1:number,arg2:string,arg3:string):Promise<void>;

export function CancelActiveTask(arg1:number,arg2:string):Promise<void>;

export function DeleteAllArchivedTasks(arg1:number,arg2:string):Promise<queue.BulkActionResult>;

export function DeleteAllCompletedTasks(arg1:number,arg2:string):Promise<queue.BulkActionResult>;

export function DeleteAllPendingTasks(arg1:number,arg2:string):Promise<queue.BulkActionResult>;

export function DeleteAllRetryTasks(arg1:number,arg2:string):Promise<queue.BulkActionResult>;

export function DeleteAllScheduledTasks(arg1:number,arg2:string):Promise<queue.BulkActionResult>;

export function DeleteQueue(arg1:number,arg2:string,arg3:boolean):Promise<void>;

export function DeleteTask(arg1:number,arg2:string,arg3:string):Promise<void>;

export function GetQueueDetail(arg1:number,arg2:string):Promise<queue.QueueDetailData>;

export function GetQueues(arg1:number):Promise<queue.QueuesData>;

export function ListActiveTasks(arg1:number,arg2:string,arg3:number,arg4:number):Promise<queue.PaginatedTaskList>;

export function ListArchivedTasks(arg1:number,arg2:string,arg3:number,arg4:number):Promise<queue.PaginatedTaskList>;

export function ListCompletedTasks(arg1:number,arg2:string,arg3:number,arg4:number):Promise<queue.PaginatedTaskList>;

export function ListPendingTasks(arg1:number,arg2:string,arg3:number,arg4:number):Promise<queue.PaginatedTaskList>;

export function ListRetryTasks(arg1:number,arg2:string,arg3:number,arg4:number):Promise<queue.PaginatedTaskList>;

export function ListScheduledTasks(arg1:number,arg2:string,arg3:number,arg4:number):Promise<queue.PaginatedTaskList>;

export function PauseQueue(arg1:number,arg2:string):Promise<void>;

export function RunAllArchivedTasks(arg1:number,arg2:string):Promise<queue.BulkActionResult>;

export function RunAllRetryTasks(arg1:number,arg2:string):Promise<queue.BulkActionResult>;

export function RunAllScheduledTasks(arg1:number,arg2:string):Promise<queue.BulkActionResult>;

export function RunTask(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UnpauseQueue(arg1:number,arg2:string):Promise<void>;
