// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['updater']['UpdaterService']['ApplyUpdate']();
}

export function CheckForUpdate() {
  return window['go']['updater']['UpdaterService']['CheckForUpdate']();
}

export function GetCurrentVersion() {
  return window['go']['updater']['UpdaterService']['GetCurrentVersion']();
}
