// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DailyStats {
    "date": string;
    "processed": number;
    "failed": number;

    /** Creates a new DailyStats instance. */
    constructor($$source: Partial<DailyStats> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("processed" in $$source)) {
            this["processed"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailyStats instance from a string or object.
     */
    static createFrom($$source: any = {}): DailyStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DailyStats($$parsedSource as Partial<DailyStats>);
    }
}

export class DashboardData {
    "queues": QueueStats[];
    "totalTasks": number;
    "totalPending": number;
    "totalActive": number;
    "totalFailed": number;
    "history": DailyStats[];
    "serverCount": number;

    /** Creates a new DashboardData instance. */
    constructor($$source: Partial<DashboardData> = {}) {
        if (!("queues" in $$source)) {
            this["queues"] = [];
        }
        if (!("totalTasks" in $$source)) {
            this["totalTasks"] = 0;
        }
        if (!("totalPending" in $$source)) {
            this["totalPending"] = 0;
        }
        if (!("totalActive" in $$source)) {
            this["totalActive"] = 0;
        }
        if (!("totalFailed" in $$source)) {
            this["totalFailed"] = 0;
        }
        if (!("history" in $$source)) {
            this["history"] = [];
        }
        if (!("serverCount" in $$source)) {
            this["serverCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DashboardData instance from a string or object.
     */
    static createFrom($$source: any = {}): DashboardData {
        const $$createField0_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("queues" in $$parsedSource) {
            $$parsedSource["queues"] = $$createField0_0($$parsedSource["queues"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField5_0($$parsedSource["history"]);
        }
        return new DashboardData($$parsedSource as Partial<DashboardData>);
    }
}

export class QueueStats {
    "queue": string;
    "size": number;
    "pending": number;
    "active": number;
    "scheduled": number;
    "retry": number;
    "archived": number;
    "completed": number;
    "processed": number;
    "failed": number;
    "processedTotal": number;
    "failedTotal": number;
    "latencyMs": number;
    "memoryUsage": number;
    "paused": boolean;

    /** Creates a new QueueStats instance. */
    constructor($$source: Partial<QueueStats> = {}) {
        if (!("queue" in $$source)) {
            this["queue"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("pending" in $$source)) {
            this["pending"] = 0;
        }
        if (!("active" in $$source)) {
            this["active"] = 0;
        }
        if (!("scheduled" in $$source)) {
            this["scheduled"] = 0;
        }
        if (!("retry" in $$source)) {
            this["retry"] = 0;
        }
        if (!("archived" in $$source)) {
            this["archived"] = 0;
        }
        if (!("completed" in $$source)) {
            this["completed"] = 0;
        }
        if (!("processed" in $$source)) {
            this["processed"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("processedTotal" in $$source)) {
            this["processedTotal"] = 0;
        }
        if (!("failedTotal" in $$source)) {
            this["failedTotal"] = 0;
        }
        if (!("latencyMs" in $$source)) {
            this["latencyMs"] = 0;
        }
        if (!("memoryUsage" in $$source)) {
            this["memoryUsage"] = 0;
        }
        if (!("paused" in $$source)) {
            this["paused"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueueStats instance from a string or object.
     */
    static createFrom($$source: any = {}): QueueStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueueStats($$parsedSource as Partial<QueueStats>);
    }
}

// Private type creation functions
const $$createType0 = QueueStats.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = DailyStats.createFrom;
const $$createType3 = $Create.Array($$createType2);
