// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scheduler} from '../models';

export function GetEnqueueEvents(arg1:number,arg2:string,arg3:number,arg4:number):Promise<scheduler.PaginatedEvents>;

export function GetSchedulerEntries(arg1:number):Promise<scheduler.SchedulersData>;

export function RunSchedulerEntry(arg1:number,arg2:string):Promise<scheduler.RunResult>;
