// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Create(arg1:domain.Environment):Promise<domain.Environment>;

export function Delete(arg1:number):Promise<void>;

export function GetAll():Promise<Array<domain.Environment>>;

export function TestConnection(arg1:domain.Environment):Promise<void>;

export function Update(arg1:domain.Environment):Promise<domain.Environment>;
