// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['environment']['EnvironmentService']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['environment']['EnvironmentService']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['environment']['EnvironmentService']['GetAll']();
}

export function TestConnection(arg1) {
  return window['go']['environment']['EnvironmentService']['TestConnection'](arg1);
}

export function Update(arg1) {
  return window['go']['environment']['EnvironmentService']['Update'](arg1);
}
