// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../../gorm.io/gorm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class Environment {
    "ID": number;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;
    "DeletedAt": gorm$0.DeletedAt;
    "Name": string;
    "Host": string;
    "Password": string;
    "DB": number;
    "UseTLS": boolean;
    "TLSSkipVerify": boolean;

    /** Creates a new Environment instance. */
    constructor($$source: Partial<Environment> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }
        if (!("DeletedAt" in $$source)) {
            this["DeletedAt"] = null;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Host" in $$source)) {
            this["Host"] = "";
        }
        if (!("Password" in $$source)) {
            this["Password"] = "";
        }
        if (!("DB" in $$source)) {
            this["DB"] = 0;
        }
        if (!("UseTLS" in $$source)) {
            this["UseTLS"] = false;
        }
        if (!("TLSSkipVerify" in $$source)) {
            this["TLSSkipVerify"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Environment instance from a string or object.
     */
    static createFrom($$source: any = {}): Environment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Environment($$parsedSource as Partial<Environment>);
    }
}
