// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {taskrunner} from '../models';

export function EnqueueTask(arg1:number,arg2:taskrunner.EnqueueRequest):Promise<taskrunner.EnqueueResult>;
