// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {taskrunner} from '../models';

export function CloneSavedRequest(arg1:number):Promise<taskrunner.SavedRequest>;

export function CreateSavedRequest(arg1:number,arg2:taskrunner.CreateSavedRequestInput):Promise<taskrunner.SavedRequest>;

export function DeleteSavedRequest(arg1:number):Promise<void>;

export function EnqueueTask(arg1:number,arg2:taskrunner.EnqueueRequest):Promise<taskrunner.EnqueueResult>;

export function GetSavedRequest(arg1:number):Promise<taskrunner.SavedRequest>;

export function GetSavedRequests(arg1:number):Promise<Array<taskrunner.SavedRequest>>;

export function RenameSavedRequest(arg1:number,arg2:taskrunner.RenameSavedRequestInput):Promise<void>;

export function UpdateSavedRequest(arg1:number,arg2:taskrunner.UpdateSavedRequestInput):Promise<taskrunner.SavedRequest>;
