// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloneSavedRequest(arg1) {
  return window['go']['taskrunner']['TaskRunnerService']['CloneSavedRequest'](arg1);
}

export function CreateSavedRequest(arg1, arg2) {
  return window['go']['taskrunner']['TaskRunnerService']['CreateSavedRequest'](arg1, arg2);
}

export function DeleteSavedRequest(arg1) {
  return window['go']['taskrunner']['TaskRunnerService']['DeleteSavedRequest'](arg1);
}

export function EnqueueTask(arg1, arg2) {
  return window['go']['taskrunner']['TaskRunnerService']['EnqueueTask'](arg1, arg2);
}

export function GetSavedRequest(arg1) {
  return window['go']['taskrunner']['TaskRunnerService']['GetSavedRequest'](arg1);
}

export function GetSavedRequests(arg1) {
  return window['go']['taskrunner']['TaskRunnerService']['GetSavedRequests'](arg1);
}

export function RenameSavedRequest(arg1, arg2) {
  return window['go']['taskrunner']['TaskRunnerService']['RenameSavedRequest'](arg1, arg2);
}

export function UpdateSavedRequest(arg1, arg2) {
  return window['go']['taskrunner']['TaskRunnerService']['UpdateSavedRequest'](arg1, arg2);
}
