// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnqueueTask(arg1, arg2) {
  return window['go']['taskrunner']['TaskRunnerService']['EnqueueTask'](arg1, arg2);
}
