// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRedisInfo(arg1) {
  return window['go']['redis']['RedisService']['GetRedisInfo'](arg1);
}
