// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {redis} from '../models';

export function GetRedisInfo(arg1:number):Promise<redis.RedisInfoData>;
