// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {worker} from '../models';

export function GetWorkers(arg1:number):Promise<worker.WorkersData>;
